### ISSUE TITLE
possible solutions

### ISSUE THREAD

**Issue by tmngtk** [siobhandougall/mavstuttering#1]
Had exactly the same problem.
- Have you tried making AppNap disabled?
- from my experience, NSThread with _while (1) {@autoreleasepool{…drawing… [glContext flushBuffer]}}_ is faster than DisplayLink. DL tries to maintain a fixed frame rate, which is just good for CoreVideo playback.

**Comment by siobhandougall** [comment]
App Nap only kicks in if the application is in the background, so it's not that.

I was having the same results with the loop approach you mention; the root problem was that `-flushBuffer` (or `glFlush()`) was blocking for an inordinately long time.

However, as of 10.10.2, as far as I can tell, this problem seems to be resolved—even though Apple closed the radar issue as "won't fix".
